name: Dill-CI-Apple

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "dev", "config-ci-cd" ]
  pull_request:
    branches: [ "main", "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: sbt

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Display Script Running
        run: echo Build beginning on Linux architecture

      - name: Run Build Script
        run: |
          echo Running build.sh
          sh build.sh

  test-laminar:
    needs: build
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: sbt

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Display Script Running
        run: echo Testing for laminar beginning on Linux architecture

      - name: Npm Installing
        run: npm install

      - name: Run Laminar Test Script
        run: sh test-laminar.sh

  test-tauri:
    needs: build
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Display Script Running 
        run: echo Testing for tauri beginning on apple architecture

      - name: Run Laminar Test Script
        run: sh test-tauri.sh
