name: Dill-CI

on:
  push:
    branches: [ "main", "dev", "config-ci-cd"]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: sbt

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Display Script Running
        run: echo Build beginning on Linux architecture

      - name: Run Build Script
        run: |
          echo Running build.sh
          sh build.sh

  test-laminar:
    needs: build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: sbt

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Display Script Running
        run: echo Testing for laminar beginning on Linux architecture

      - name: Npm Installing
        run: npm install

      - name: Run Laminar Test Script
        run: sh test-laminar.sh

  test-tauri:
    needs: build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Script Running
        run: echo Testing for tauri beginning on Linux architecture

      - name: Run Tauri Test Script
        run: sh test-tauri.sh
