name: Dill-CI

# Defines when the pipeline will be invoked
on:
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches:
      - main 
      - dev
  # Allows us to run the workflow whenever we want from GitHub Actions
  workflow_dispatch:

jobs:
  build:
    # Creates a job for each OS
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: sbt

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Display Script Running
        run: echo Build beginning on $RUNNER_OS architecture

      - name: Run Build Script
        shell: bash
        run: |
          echo Running build.sh
          sh build.sh

  test-laminar:
    # Requires that build job is completed first
    needs: build
    # Creates a job for each OS
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: sbt

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Display Script Running
        run: echo Testing for laminar beginning on $RUNNER_OS architecture

      - name: Npm Installing
        run: npm install

      - name: Run Laminar Test Script
        shell: bash
        run: sh test-laminar.sh

  test-tauri:
    # Requires that build job is completed first
    needs: build
    # Creates a job for each OS
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Script Running
        run: echo Testing for tauri beginning on $RUNNER_OS architecture

      - name: Run Tauri Test Script
        shell: bash
        run: sh test-tauri.sh
