name: Dill-CI

# Defines when the pipeline will be invoked
on:
  push:
    branches: 
      - main
      - dev
      
  pull_request:
    branches:
      - main 
      - dev

  # Allows us to run the workflow whenever we want from GitHub Actions
  workflow_dispatch:

jobs:
  build:
    name: Check, test and build DILL

    # Creates a job for each OS
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      
      # Use composite action for setup 
      - name: Setup 
        uses: ./.github/actions/setup

      - name: Check backend compiles
        shell: bash
        run: |
          cd src-tauri
          cargo check

      - name: Test backend
        shell: bash
        run: sh scripts/test-tauri.sh

      - name: Test frontend
        shell: bash
        run: sh scripts/test-laminar.sh

      - name: Build artefact
        shell: bash
        run: |
          sh scripts/build.sh