name: Dill-CI

on:
  push:
    branches: 
      - main
      - dev
    
  pull_request:
    branches:
      - main
      - dev

  # Allows us to run the workflow whenever we want from GitHub Actions
  workflow_dispatch:
        

concurrency:
  group: dill-ci-${{ github.ref }}
  cancel-in-progress: true


jobs:
  pipeline:

    strategy:
      matrix:
        include:
          - platform: 'ubuntu-latest'
          - platform: 'macos-latest'
          - platform: 'windows-latest'

    runs-on: ${{ matrix.platform }}


    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt install libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          
      - name: Install Node dependencies
        run: npm install
    
      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
  
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      
      - name: Clean SBT caches and set env (Windows only)
        if: matrix.platform == 'windows-latest'
        shell: bash
        run: |
          rm -rf "$GITHUB_WORKSPACE/.coursier-cache"
          rm -rf "C:/Users/runneradmin/.ivy2/cache"
          rm -rf "C:/Users/runneradmin/.sbt"
          echo "SBT_OPTS=-Dfile.encoding=UTF-8" >> $GITHUB_ENV
          
      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: sbt

      
      - name: Install Coursier (Windows only)
        if: matrix.platform == 'windows-latest'
        run: |
          curl -fLo cs.exe https://git.io/coursier-cli
          chmod +x cs.exe
          echo "PATH=$PATH:$PWD" >> $GITHUB_ENV
      
      - name: Install Coursier (Linux and macOS)
        if: matrix.platform == 'ubuntu-latest' || matrix.platform == 'macos-latest'
        shell: bash
        run: |
          curl -fLo cs https://git.io/coursier-cli
          chmod +x cs
          echo "PATH=$PATH:$PWD" >> $GITHUB_ENV

      - name: Pre-fetch Scala 3 Compiler (Windows only)
        if: matrix.platform == 'windows-latest'
        run: ./cs.exe fetch org.scala-lang:scala3-compiler_3:3.3.3

      - name: Pre-fetch Scala 3 Compiler (Linux and macOS)
        if: matrix.platform == 'ubuntu-latest' || matrix.platform == 'macos-latest'
        run: ./cs fetch org.scala-lang:scala3-compiler_3:3.3.3

      - name: Update sbt
        shell: bash
        run: sbt update

      - name: Test frontend
        shell: bash
        run: sbt test


      - name: Test backend
        run: |
          cd src-tauri
          cargo test
