name: Dill-CI-Linux

on:
  push:
    branches: [ "main", "dev", "config-ci-cd", "debug-ci-cd" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: sbt

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Test sbt version
        run: sbt --version

      # Check Node.js version
      - name: Check Node.js version
        run: node --version

      # Check TypeScript version
      - name: Check TypeScript version
        run: npx tsc --version

      - name: Display Script Running
        run: echo Build beginning on Linux architecture

      - name: Run Build Script
        run: |
          echo Running build.sh
          sh build.sh

  test-laminar:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: sbt

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Test sbt version
        run: sbt --version

      - name: Display Script Running
        run: echo Testing for laminar beginning on Linux architecture

      - name: Npm Installing
        run: npm install

      - name: Run Laminar Test Script
        run: sh test-laminar.sh

  test-tauri:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Script Running
        run: echo Testing for tauri beginning on Linux architecture

      - name: Run Tauri Test Script
        run: sh test-tauri.sh
